function GetValue()
{
    var myarray= new Array("I’d rather reschedule my knee surgery than not being with you",
  "lets skibidi into the sunset",
  "id pause my subway surfers gameplay to be with you",
  "your the solulu to my delulu",
  "are you a cat? bc you make me mew",
  "with me and you, we’ll never be cooked",
  "i go “erm what the sigma” when i see you",
  "not being with you would give -10000 aura",
  "if being with anyone but you is an L, I’ll take the L.",
  "uwu hewwo owo xwx",
  "do you know da wey to my heart <3",
  "are you an imposter? bc youve taken my heart",
  "bruh no cap our aura together is high key bussin",
  "are you an ipad because i dont want to be without you",
  "are you thinking of joining a look-alike  contest? Because you look like the love of my life.",
  "chill Guy, Bottom Text",
  "are you the rizzler because im stickin my gyatt out for you",
  "im holding space to defy gravity with you",
  "your so skibidi i gyatt to be with you",
  "lets be chill together",
  "being with me is a w",
  "im not tweaking when i say i want to lock in and touch grass with you",
  "my mother said “Queen Never Cry” so im locking in to make you the love of your life",
  "your so sigma its gyatt to be a dream",
  "lets skibi-be together ;)",
  "thank Beyonce for giving me you",
  "be the duo to my Fortnite",
  "are you looks maxxing because gyatt dang ;)",
  "are you Ohio because TOP TEXT",
  "will you spend this skibidi rizzmas with me",
  "our vibes are no cap high key sigma we gyatt to be together",
  "will you be part of my symphony?",
  "be the hawk to my tuah",
  "be the Gegagedigedagedago to my Max",
  "you have the lvl 100 gyatt to my lvl 100 sigma."
);
    var random = myarray[Math.floor(Math.random() * myarray.length)];
    document.getElementById("Rizzponse").innerHTML=random; }